services:
    postgres:
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: sustn
            POSTGRES_PASSWORD: sustn
            POSTGRES_DB: sustn
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
